name: flutter_getx_template
description: Flutter with Getx Template.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_animations: ^1.1.1
  flutter_map: ^4.0.0
  flutter_easyloading: ^3.0.5
  flutter_svg: ^2.0.7
  flutter_html: any
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^14.1.1
  flutter_rating_bar: ^4.0.1
  flutter_native_splash: ^2.3.1
  flutter_inappwebview: ^5.7.2+3
  firebase_core: ^2.13.1
  firebase_messaging: ^14.6.2
  firebase_crashlytics: ^3.3.2
  connectivity_plus: ^4.0.1
  path_provider_android: ^2.0.27
  path_provider_ios: ^2.0.11
  carousel_slider: ^4.2.1
  webview_flutter: ^4.2.2
  geolocator: ^9.0.2
  latlong2: ^0.8.0
  maps_toolkit: ^2.0.1
  awesome_dialog: any
  intl: ^0.18.1
  dio: ^5.2.1+1
  dio_http2_adapter: ^2.3.0
  localstorage: ^4.0.1+2
  url_launcher: ^6.1.11
  fimber: ^0.6.6
  google_fonts: ^4.0.4
  dropdown_button2: ^2.1.3
  mask_text_input_formatter: ^2.4.0
  camera: ^0.10.5+2
  lottie: ^2.4.0
  octo_image: ^1.0.2
  upgrader: ^6.5.0
  path: any
  infinite_scroll_pagination: ^3.2.0
  permission_handler: any
  mockito: ^5.4.2
  google_mlkit_face_detection: ^0.7.0
  percent_indicator: ^4.2.3
  timezone: any
  shimmer: ^3.0.0
  file_picker: ^5.3.0
  image_picker: ^0.8.7+5
  syncfusion_flutter_pdfviewer: ^21.2.8

  #  --- Alpha/Beta/Release Candidate Libraries ---
  get: ^5.0.0-release-candidate-4
  location: ^5.0.0-dev.8

#  --- Unused Libraries ---
#  package_info_plus: ^3.0.3
#  flutter_pdfview: ^1.2.9
#  file: ^7.0.0
#  overlay_support: any
#  safe_device: ^1.1.2
#  basic_utils: ^5.5.4
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_lints: ^2.0.2
  pigeon: ^10.1.2
  pub_semver: ^2.1.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/ic_application.png"
  remove_alpha_ios: true

flutter_native_splash:
  web: false
  color: "#FFFFFF"
  image: "assets/icon/ic_application.png"
  color_dark: "#FFFFFF"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/vector/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
